"""empty message

Revision ID: 50da4769dfa2
Revises: 
Create Date: 2019-11-18 13:57:29.851490

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50da4769dfa2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog', sa.Column('view_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blog', 'view_count')
    # ### end Alembic commands ###
